# Задание 3. Реализация собственных исключений

## Предыстория
В PHP существует механизм исключений. Небольшое напоминание про то, как они выглядят:
 * [Исключения](https://www.php.net/manual/ru/language.exceptions.php)
 
Но не всегда нам нужно использовать существующие, например, бывает необходимость в своих, кастомных
исключениях. Поэтому на данном, возможно искусственном, примере мы рассмотрим использование исключений
для конкретизации ошибок. 

## Техническое задание
Попробуем отследить тип переменной, переданной в функцию, с помощью исключений.

Создайте "кастомные" исключения, которые обозначали бы:
* int число
* float число
* string строка
* bool булево значение
* array массив
* null объект

Как примерно будет выглядеть результат:
* вызываем функцию calculate,
* внутри функции, в зависимости от типа переданной переменной, выбрасываем то или иное исключение (из созданных выше),
* снаружи ловим каждое отдельное исключение и в его блоке catch выводим сообщение о типе переменной.

### Задание со звездочкой
Внедрите свои классы исключений в качестве проверок в задание 02 (с сотрудниками отдела). 
Пример:
* передали отрицательное значение зарплаты - исключение "зарплата не может быть меньше 0" и вывод соответствующего 
сообщения.

**Обратите внимание на** [**рекомендации по сдаче домашнего задания**](../homework.md). 